---
## Workflow to create a new git tag if version.py variable version gets updated
name: release

permissions:
  contents: write # write permission is required to create a GitHub release

on:
  push:
    branches:
      - 'main'
      - 'test/support-sar-automation'
    paths:
      - 'share/version.py'
      - '.github/workflows/release.yml'

jobs:
  regular-sar:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      BUCKET_NAME : "esf-dependencies"
      AWS_REGION : "eu-central-1"
      # elastic-observability-prod
      AWS_ACCOUNT_ID: "627286350134"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "lambda-v1.17.0"

      - uses: elastic/oblt-actions/aws/auth@v1
        with:
          aws-account-id: "${{ env.AWS_ACCOUNT_ID}}"
          aws-region: "${{ env.AWS_REGION }}"

      - uses: aws-actions/setup-sam@2360ef6d90015369947b45b496193ab9976a9b04 # v2
        with:
          use-installer: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and package
        run: |
          .internal/aws/scripts/dist.sh \
            elastic-serverless-forwarder \
            1.17.0 \
            victor-martinez-sar-testing \
            ${{ env.AWS_ACCOUNT_ID }} \
            ${{ env.AWS_REGION }} \
            "GitHub Bot"
